### ISSUE TITLE
Add more flight case lore

### ISSUE THREAD

**Issue by JoshHeng** [WarwickTechCrew/website#10]

**Comment by k-shar** [comment]
Has this been done? / what lore do we need to document

**Comment by JoshHeng** [comment]
Idk just if there's more lore about each flight case, the page is quite empty

**Comment by k-shar** [comment]
dave pizza delivery for freshers 

![image](https://github.com/user-attachments/assets/b8c7d75c-099b-4a11-b968-adaaa8571210)
- [ ] crop and compress ect this image

**Comment by k-shar** [comment]
added steve tesco lore
