### ISSUE TITLE
Add IRL pictures

### ISSUE THREAD

**Issue by JoshHeng** [WarwickTechCrew/website#11]
Someone on campus will need to go and take pictures of:
- [ ] avon cupboard picture
- [x] each flightcase

**Comment by k-shar** [comment]
- [ ] storage locations
- [ ] each flightcase

**Comment by k-shar** [comment]
george image of dave 

![image](https://github.com/user-attachments/assets/ad1afdb2-9689-47a4-8540-058aca8c8573)
- [ ] crop compress credit george and upload

**Comment by k-shar** [comment]
- [ ] avon cupboard picture
