### ISSUE TITLE
Fix contributor name mapping 

### ISSUE THREAD

**Issue by k-shar** [WarwickTechCrew/website#15]
https://dev.warwicktechcrew.co.uk/wiki/warwick-drama

![image](https://github.com/user-attachments/assets/1a2baa9e-d6dd-4a57-abe1-01f6d945fffa)

**Comment by JoshHeng** [comment]
Kishan stop changing ur name!!!!

**Comment by k-shar** [comment]
> Kishan stop changing ur name!!!!

my name is kIsHaN please

**Comment by JoshHeng** [comment]
I mean my phone always autocorrects your name to KISHAN
