### ISSUE TITLE
Fix icon in Google search

### ISSUE THREAD

**Issue by JoshHeng** [WarwickTechCrew/website#24]
There is no icon on indexed results in Google. I'm guessing this is because the favicon is an SVG - we should maybe use a png or ico one instead.

![image](https://github.com/user-attachments/assets/470aedb7-7cc7-405b-9170-60b31548b56f)

**Comment by JoshHeng** [comment]
This has been replaced with an .ico, I guess let's see if this works

**Comment by k-shar** [comment]
dont think so :(

![image](https://github.com/user-attachments/assets/c183cb87-d899-4ab1-b4e8-1fe0abcf52ac)

**Comment by k-shar** [comment]
still broken

**Comment by JoshHeng** [comment]
Looks like it's fixed!
