### ISSUE TITLE
Replace WAC technician names

### ISSUE THREAD

**Issue by JoshHeng** [WarwickTechCrew/website#29]

**Comment by k-shar** [comment]
i think this is worthwhile doing:
1. for their personal privacy
2. we said stuff like "A member of WAC staff (typically Amanda) will watch the dress and give the tech team notes immediately after in the auditorium." which is a bit of an obligation to put on that one person when they might not wish to continue doing this to the same extent in the future
3. if wac staff changes/ our point of contact changes it is a bit effort to rename all the references ect

So i think we should stick to generic WAC staff, WAC technician, duty technician for the wiki
