### ISSUE TITLE
percy doesn't have pronouns on the wiki :(((

### ISSUE THREAD

**Issue by DinoExho** [WarwickTechCrew/website#36]
i know percy has pronouns but i can't remember what they are and they should be on the wiki so i can check

**Comment by JoshHeng** [comment]
@DinoExho This would be an excellent first issue to work on!!

**Comment by k-shar** [comment]
![20240926_174846.jpg](https://github.com/user-attachments/assets/d9a72398-c47d-4cd0-83cb-f72c5eb20b2b)

**Comment by DinoExho** [comment]
pronouns updated yippee

**Comment by JoshHeng** [comment]
Yay nice thanks!!
