### ISSUE TITLE
author credit broke again

### ISSUE THREAD

**Issue by k-shar** [WarwickTechCrew/website#50]
page says josh wrote all but kishan wrote some

https://github.com/WarwickTechCrew/website/blame/main/wiki/02-warwick-drama/01-drama-collective/index.md
https://www.warwicktechcrew.co.uk/wiki/warwick-drama/drama-collective
![image](https://github.com/user-attachments/assets/d9d7eb82-6751-4b3d-9ad3-5ad5f4f1e560)
![image](https://github.com/user-attachments/assets/5e99b473-e32e-4eeb-a171-af35d5e09c9e)

initial investigation shows git knows the commit exists
![image](https://github.com/user-attachments/assets/74703886-ee2c-413e-bfcc-e29fac115b73)
![image](https://github.com/user-attachments/assets/d31ec9bc-bea7-4962-8103-a007d6d716ba)

**Comment by k-shar** [comment]
never mind that code is wrong it does commits.find not filteredCommits.find nvm

**Comment by JoshHeng** [comment]
Fixed, for some reason i forgot to set follow to true
