### ISSUE TITLE
Bad changelog link 

### ISSUE THREAD

**Issue by JoshHeng** [WarwickTechCrew/website#55]
https://www.warwicktechcrew.co.uk/wiki/warwick-drama/shows/show-week/show-week

Should be

https://www.warwicktechcrew.co.uk/wiki/warwick-drama/shows/show-week

<img width="358" alt="image" src="https://github.com/user-attachments/assets/9ad4d786-f4e3-4540-88c6-dfe329c26812">

**Comment by DinoExho** [comment]
where even is that

**Comment by k-shar** [comment]
@DinoExho https://www.warwicktechcrew.co.uk/wiki/resources/changelog
