### ISSUE TITLE
Make images side by side

### ISSUE THREAD

**Issue by k-shar** [WarwickTechCrew/website#61]
For some reason the dock page uses:
```
<div class="img-gallery">
    ![Warwick Arts Centre Dock](./dock-joshheng.jpg)
    ![Warwick Arts Centre Dock](./wac-joshheng.jpg)
</div>
```
but the images dont render side by side
https://www.warwicktechcrew.co.uk/wiki/tech-crew/storage/the-dock

![image](https://github.com/user-attachments/assets/3daaf8dd-0df1-4b26-a784-62392683ee91)

can someone spot how im being silly please

**Comment by k-shar** [comment]
link was borked nvm

**Comment by k-shar** [comment]
lied

**Comment by k-shar** [comment]
images are too wide so it dosent side by side them

**Comment by MattA-Official** [comment]
You should use a flexbox for this. I'll fix it tomorrow and open a PR.

**Comment by JoshHeng** [comment]
@MattA-Official A flexbox is already used, the issue is the images are too wide as the size is determined by height. This can likely be decreased by reducing the height to 17rem or something instead of 18rem.

Is this something you still wanna do?

**Comment by MattA-Official** [comment]
> Is this something you still wanna do?
I'll do it at some point when I have some time, unless anyone else wants to do it before me.

**Comment by JoshHeng** [comment]
Done during fixing another issue
