### ISSUE TITLE
Strip trailing non-text characters from URLs

### ISSUE THREAD

**Issue by JoshHeng** [WarwickTechCrew/website#71]
[https://www.warwicktechcrew.co.uk/equipment-directory!](https://www.warwicktechcrew.co.uk/equipment-directory!)

This leads to a 404. We should instead redirect to https://www.warwicktechcrew.co.uk/equipment-directory

**Comment by k-shar** [comment]
is this a standard/ common thing to do?
for example [https://docusaurus.io/docs/configuration!](https://docusaurus.io/docs/configuration!) dosen't do this.
idk if it makes things weird with routing

**Comment by JoshHeng** [comment]
Fixed with a cloudflare redirect rule, see README for more details
