### ISSUE TITLE
Non-HTTPS wwtc links do not resolve

### ISSUE THREAD

**Issue by JoshHeng** [WarwickTechCrew/website#91]
http://wwtc.uk doesn't seem to resolve or redirect

**Comment by k-shar** [comment]
sends me to https://www.warwicktechcrew.co.uk/
https://whatismybrowser.com/w/7WLP789

**Comment by JoshHeng** [comment]
Doesn't seem to work for me on iOS/safari

**Comment by k-shar** [comment]
common apple L
