### ISSUE TITLE
Create embed image for brand page

### ISSUE THREAD

**Issue by JoshHeng** [WarwickTechCrew/website#94]
Create an embed image to brand page with a clear CTA. Hopefully this can be indexed fairly high when someone googles the tc logo to get them to visit the page rather than copying the top Google image result

**Comment by k-shar** [comment]
CTA stands for ?

**Comment by JoshHeng** [comment]
Call to Action

As in the image would say something like

Warwick Tech Crew Logo & Brand Guidelines

Please Read at https://wwtc.uk/brand
